In [1]:
import numpy #numpy는 numpy array라는 새로운 자료형을 추가해줘 연산이 쉽게 가능하도록 함

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(11,)

In [6]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array2.shape # 행이 3개이고 열이 4인 2차원 배열

(3, 4)

In [11]:
array1.size # numpy array에 총 몇 개의 요소가 있는지 

11

In [12]:
array2.size

12

#### numpy array를 만드는 다양한 방법

##### 1. 파이썬 리스트를 통해 생성

In [13]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


##### 2. 균일한 값으로 생성

full 메소드의 활용

In [14]:
array1 = numpy.full(6, 7) 
print(array1)

[7 7 7 7 7 7]


모든 값이 0인 numpy array 생성

In [15]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype = int)

print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


모든 값이 1인 numpy array 생성

In [18]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype = int)

print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


랜덤한 값들로 생성, numpy 안의 random 모듈의 random 함수 사용.(0~1 사이의 값) cf. 파이썬 random 모듈, randint.

In [20]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

print(array1)
print()
print(array2)

[0.65483005 0.71474682 0.92503131 0.19282358 0.61300101 0.1047238 ]

[0.26113928 0.87820468 0.58024716 0.0079154  0.05856553 0.13932147]


##### 연속된 값들이 담긴 numpy array 생성

arrange 함수 사용, 파이썬 기본 함수 range랑 비슷한 원리로 동작

파라미터 1개

In [22]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


파라미터 2개

In [23]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


파라미터 3개

In [24]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


#### 모듈 별명 지어주기

In [25]:
import numpy as np

In [28]:
array1 = np.full(6, 0)
array2 = np.zeros(6, dtype = int)

print(array1)
print(array2)

[0 0 0 0 0 0]
[0 0 0 0 0 0]


#### 인덱싱과 슬라이싱

In [29]:
import numpy as np

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

인덱싱

In [31]:
array1[0]

2

In [32]:
array1[2]

5

In [33]:
array1[-1]

31

리스트로 인덱싱 하기

In [34]:
array1[[1, 3, 4]] # 일반 리스트를 리스트로 인덱싱하는 것은 안됨.

array([ 3,  7, 11])

numpy array로 인덱싱하기 

In [35]:
array2 = np.array([2, 1, 3])

In [36]:
array1[array2]

array([5, 3, 7])

슬라이싱

In [37]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [39]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [40]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

#### numpy 기본 연산

In [41]:
import numpy as np

In [42]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [43]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
array1 * 2 # numpy가 없으면 반복문 사용해야함

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [48]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [50]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
array1 = array1 * 2 # 저장을 다시 해줘야 반영됨

In [52]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [55]:
array1 + array2 # array 길이가 같아야함

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [56]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [57]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [58]:
array1 // array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
array1 % array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 불린 연산

In [60]:
import numpy as np

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [61]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [62]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [63]:
booleans = np.array([True, True, False, True, True, False, True, True, False, False])

numpy where함수 활용, 해당하는 인덱스 위치 찾고 이를 활용하여 numpy array에서 조건에 만족하는 값 찾기

In [64]:
np.where(booleans)

(array([0, 1, 3, 4, 6, 7]),)

In [65]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [66]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [68]:
array1[filter] #특정 조건을 만족시키는 값만 뽑아내기

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

##### numpy 기본 통계

최댓값(max), 최솟값(min)

In [1]:
import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max())
print(array1.min())

31
5


평균값(mean), 중앙값(median)

In [3]:
import numpy as np

array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])
array2 = np.array([8, 12, 9, 15, 16])

print(array1.mean())

print(np.median(array1))
print(np.median(array2)) #median은 numpy의 메소드임



15.25
13.5
12.0


표준편차(std)와 분산(var)

In [5]:
print(array1.std())
print(array1.var())

8.496322733983215
72.1875


In [7]:
 array1 = np.array(['doadasd', 50, 50]) # 질문 확인

In [8]:
print(type(array1))

<class 'numpy.ndarray'>
